name: PipeLine

on:
  workflow_dispatch:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest jq

      - name: SonarQube Scan
        id: sonar
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_PROJECT_KEY: Neyvk_DevOps-retake
          SONAR_ORGANIZATION: neyvk
          SONAR_BRANCH: dev

      - name: Wait for SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          TASK_ID="${{ steps.sonar.outputs.ceTaskId }}"
          echo "Waiting for analysis $TASK_ID to complete..."

          STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/ce/task?id=$TASK_ID" | jq -r '.task.status')
          while [ "$STATUS" != "SUCCESS" ] && [ "$STATUS" != "FAILED" ]; do
            echo "Analysis not finished yet, waiting 10s..."
            sleep 10
            STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/ce/task?id=$TASK_ID" | jq -r '.task.status')
          done

          if [ "$STATUS" == "FAILED" ]; then
            echo "SonarCloud analysis failed!"
            exit 1
          fi

          echo "Analysis completed successfully!"


      - name: Download SonarCloud report
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          curl -L -u $SONAR_TOKEN: \
          -X GET "https://sonarcloud.io/api/regulatory-reports?projectKey=Neyvk_DevOps-retake&branchKey=dev" \
          -H "accept: application/zip" \
          -o sonar_report.zip

      - name: Upload SonarCloud report as artifact
        uses: actions/upload-artifact@v6
        with:
          name: sonar_report
          path: sonar_report.zip

      - name: Send Telegram notification
        run: python send_notification.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_SOURCE_BRANCH: ${{ github.event.pull_request.head.ref }}
          PR_TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          RELEASE_TAG: ${{ github.ref_name }}
